language: node_js
node_js: node
script: yarn run fulltest && cp .env.example .env && yarn run build && yarn run submit-coverage
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
