language: node_js
node_js: node
script: yarn run test && cp .env.example .env && yarn run build && ( yarn run coverage:submit || true )
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
