// flow-typed signature: 172b11bdce21251ca310525575d05911
// flow-typed version: <<STUB>>/dotenv-webpack_v^1.6.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv-webpack/browser' {
  declare module.exports: any;
}

declare module 'dotenv-webpack/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dotenv-webpack/browser.js' {
  declare module.exports: $Exports<'dotenv-webpack/browser'>;
}
declare module 'dotenv-webpack/dist/index.js' {
  declare module.exports: $Exports<'dotenv-webpack/dist/index'>;
}
declare module 'dotenv-webpack/index' {
  declare module.exports: $Exports<'dotenv-webpack'>;
}
declare module 'dotenv-webpack/index.js' {
  declare module.exports: $Exports<'dotenv-webpack'>;
}
