// flow-typed signature: 3e9f7e51a8c355cf8b25d0b78516337c
// flow-typed version: <<STUB>>/eslint-config-jest-enzyme_v^7.0.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-jest-enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-jest-enzyme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-jest-enzyme/index' {
  declare module.exports: $Exports<'eslint-config-jest-enzyme'>;
}
declare module 'eslint-config-jest-enzyme/index.js' {
  declare module.exports: $Exports<'eslint-config-jest-enzyme'>;
}
