// flow-typed signature: c4f341b2d3c2535b0621faeca8e75d7b
// flow-typed version: <<STUB>>/jest-environment-enzyme_v^7.0.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-environment-enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-environment-enzyme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-environment-enzyme/lib/index' {
  declare module.exports: any;
}

declare module 'jest-environment-enzyme/lib/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-environment-enzyme/lib/index.js' {
  declare module.exports: $Exports<'jest-environment-enzyme/lib/index'>;
}
declare module 'jest-environment-enzyme/lib/setup.js' {
  declare module.exports: $Exports<'jest-environment-enzyme/lib/setup'>;
}
