// flow-typed signature: a8e985879f80ae2e1f4fe5c7b860c80e
// flow-typed version: <<STUB>>/supertest_v^4.0.2/flow_v0.102.0-rc

/**
 * This is an autogenerated libdef stub for:
 *
 *   'supertest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'supertest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'supertest/lib/agent' {
  declare module.exports: any;
}

declare module 'supertest/lib/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'supertest/index' {
  declare module.exports: $Exports<'supertest'>;
}
declare module 'supertest/index.js' {
  declare module.exports: $Exports<'supertest'>;
}
declare module 'supertest/lib/agent.js' {
  declare module.exports: $Exports<'supertest/lib/agent'>;
}
declare module 'supertest/lib/test.js' {
  declare module.exports: $Exports<'supertest/lib/test'>;
}
