// flow-typed signature: ce22ac9fb1d00fc0e4e6ffddebbe8420
// flow-typed version: <<STUB>>/typeface-roboto_v^0.0.75/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto' {
  declare module.exports: any;
}
