// flow-typed signature: 2eaf3058591388063e6b546940f3eddc
// flow-typed version: <<STUB>>/typeface-roboto_v^0.0.54/flow_v0.102.0-rc

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto' {
  declare module.exports: any;
}
