// flow-typed signature: 5e6742648c6fb2a584a8647d9336a17d
// flow-typed version: <<STUB>>/universal-cookie-express_v^3.0.7/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'universal-cookie-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'universal-cookie-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'universal-cookie-express/cjs/index' {
  declare module.exports: any;
}

declare module 'universal-cookie-express/es6/index' {
  declare module.exports: any;
}

declare module 'universal-cookie-express/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'universal-cookie-express/cjs/index.js' {
  declare module.exports: $Exports<'universal-cookie-express/cjs/index'>;
}
declare module 'universal-cookie-express/es6/index.js' {
  declare module.exports: $Exports<'universal-cookie-express/es6/index'>;
}
declare module 'universal-cookie-express/lib/index.js' {
  declare module.exports: $Exports<'universal-cookie-express/lib/index'>;
}
