// flow-typed signature: 995798d4f7412bcf5851b71c09f4f928
// flow-typed version: <<STUB>>/universal-cookie-express_v^4.0.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'universal-cookie-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'universal-cookie-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'universal-cookie-express/cjs' {
  declare module.exports: any;
}

declare module 'universal-cookie-express/es6' {
  declare module.exports: any;
}

declare module 'universal-cookie-express/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'universal-cookie-express/cjs/index' {
  declare module.exports: $Exports<'universal-cookie-express/cjs'>;
}
declare module 'universal-cookie-express/cjs/index.js' {
  declare module.exports: $Exports<'universal-cookie-express/cjs'>;
}
declare module 'universal-cookie-express/es6/index' {
  declare module.exports: $Exports<'universal-cookie-express/es6'>;
}
declare module 'universal-cookie-express/es6/index.js' {
  declare module.exports: $Exports<'universal-cookie-express/es6'>;
}
declare module 'universal-cookie-express/lib/index' {
  declare module.exports: $Exports<'universal-cookie-express/lib'>;
}
declare module 'universal-cookie-express/lib/index.js' {
  declare module.exports: $Exports<'universal-cookie-express/lib'>;
}
