// @flow
export const OPEN_CREATE_DIALOG = "OPEN_CREATE_DIALOG";
export const OPEN_UPDATE_DIALOG = "OPEN_UPDATE_DIALOG";
export const UPDATE_DIALOG = "UPDATE_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";

export const DIALOG_TYPE_CREATE = "DIALOG_TYPE_CREATE";
export const DIALOG_TYPE_UPDATE = "DIALOG_TYPE_UPDATE";
